let repeatNumber = document.querySelector('#repeatNumber')
let addNumber = document.querySelector('#addNumber')
let gameOver = document.querySelector('#gameOver')
let opening = document.querySelector('#opening')
let winGame = document.querySelector('#winGame')
let popUp = document.querySelector('#popUp')
let characterSound = document.querySelector('#characterSound')