const repeatNumber = document.querySelector('#repeatNumber')
const addNumber = document.querySelector('#addNumber')
const gameOver = document.querySelector('#gameOver')
const opening = document.querySelector('#opening')
const winGame = document.querySelector('#winGame')
const popUp = document.querySelector('#popUp')
const characterSound = document.querySelector('#characterSound')