const repeatNumberSound = document.querySelector('#repeatNumber')
const addNumberSound = document.querySelector('#addNumber')
const gameOverSound = document.querySelector('#gameOver')
const openingSound = document.querySelector('#opening')
const winGameSound = document.querySelector('#winGame')
const popUpSound = document.querySelector('#popUp')
const characterSound = document.querySelector('#characterSound')