numberGuess.addEventListener("keyup", guessMachine)
numberGuess.addEventListener("focusin",goToNewRow)

playButton.addEventListener("click", skipSection)
infoButton.addEventListener("click", playPopUpSound)
resetButton.addEventListener("click", reset)
statsButton.addEventListener("click", playPopUpSound)
rankingButton.addEventListener("click", playPopUpSound)
buttonCollapse.addEventListener("click", playPopUpSound)
buttonCollapse.addEventListener("click", handleButtonCollapse)
inputGroup.addEventListener("change",handleRadioButtonChange)
buttonSaveUser.addEventListener("click", saveInputName)


btnCloseResult.addEventListener("click",goToTop)
btnCloseResult2.addEventListener("click",goToTop)
btnCloseInfo.addEventListener("click",goToInput)
btnCloseInfo2.addEventListener("click",goToInput)
btnCloseStats.addEventListener("click",goToInput)
btnCloseStats2.addEventListener("click",goToInput)