numberGuess.addEventListener("keyup", guessMachine)
numberGuess.addEventListener("focusin", ()=>{goToNewRow()})
resetButton.addEventListener("click", reset)
infoButton.addEventListener("click", playPopUpSound)
statsButton.addEventListener("click", playPopUpSound)
playButton.addEventListener("click", skipSection)
buttonCollapse.addEventListener("click", handleButtonCollapse)
inputGroup.addEventListener("change",handleRadioButtonChange)
btnCloseResult.addEventListener("click",goToTop)
btnCloseResult2.addEventListener("click",goToTop)
btnCloseInfo.addEventListener("click",goToInput)
btnCloseInfo2.addEventListener("click",goToInput)
btnCloseStats.addEventListener("click",goToInput)
btnCloseStats2.addEventListener("click",goToInput)