const radioDiv = document.querySelector("#radioDiv")
const inputGroup = document.querySelector("#inputGroup")
const buttonCollapse = document.querySelector('#buttonCollapse')
const btnradio1 = document.querySelector("#btnradio1")
const btnradio2 = document.querySelector("#btnradio2")
const btnradio3 = document.querySelector("#btnradio3")